myshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views



urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include('shop.urls')),

    url(r'^users/logout/$', auth_views.logout, kwargs={'next_page': 
       'main'}, name='auth_logout'),
    url(r'^users/', include('registration.backends.simple.urls',
       namespace='users')),
]

shop/urls.py
from django.conf.urls import url
from . import views
from myshop.settings import MEDIA_ROOT, DEBUG
from django.conf.urls.static import static
from django.conf import settings
from shop.views import FlowerDelete




urlpatterns = [

    url(r'^$', views.main_page, name='main'),
    url(r'^pro_mene/', views.about_me, name='about'),
    url(r'^kontakty', views.contacts, name='contacts'),
    #url(r'^koshyk', views.basket, name='basket'),
    url(r'^basket', views.basket, name='basket'),
    url(r'^samovlenya', views.orders, name='orders'),

    url(r'^flower/(?P<pk>\d+)/one/', views.one_flower, name='one_flower'),

    url(r'^kupyty/', views.main_page, name='buy'),
    url(r'^oformlenya_zamovlenya/', views.OrderCreate, name='OrderCreate'),

    url(r'^dodaty_kvitku', views.flower_add, name='flower_add'),
    url(r'^redahuvaty/(?P<pk>\d+)/kvitku', views.flower_edit, name='flower_edit'),
    url(r'^vydalyty/(?P<pk>\d+)/kvitku', FlowerDelete.as_view(), name='flower_del'),

    url(r'^order/(?P<pk>\d+)/one/', views.one_order, name='one_order'),
    url(r'^add/(?P<flower_id>\d+)/$', views.CartAdd, name='CartAdd'),
    url(r'^ad/(?P<flower_id>\d+)/$', views.CartAdd_basket, name='CartAdd_basket'),
    url(r'^remove/(?P<flower_id>\d+)/$', views.CartRemove, name='CartRemove'),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Flower(models.Model):

	class Meta(object):
		verbose_name = u'Квітка'
		verbose_name_plural = u'Квіти'

	title = models.CharField(
      max_length=256,
      blank=False)
	lat_title = models.CharField(
      max_length=256,
      blank=False)
	price = models.CharField(
      max_length=256,
      blank=False)
	description = models.TextField(
      blank=False)
	photo_main = models.ImageField(
      blank=False,
      null=False)
	photo_big = models.ImageField(
      blank=True,
      null=True)
	def __unicode__(self):
		return u'%s' % (self.title)





class Order(models.Model):

	class Meta(object):
		verbose_name = u'Замовлення'
		verbose_name_plural = u'Замовлення'

	name = models.CharField(
      max_length=256,
      blank=False)
	number = models.CharField(
      max_length=256,
      blank=False)
	notes = models.TextField(
      blank=True)
	total_cost = models.CharField(
    max_length=256,
	  blank=False)
	def get_total_cost(self):
		return sum(item.get_cost() for item in self.items.all())

	def __unicode__(self):
		return u'%s' % (self.name)






class OrderItem(models.Model):
    order = models.ForeignKey(Order,
     related_name='items')
    product = models.ForeignKey(Flower,
     related_name='order_items')
    price = models.DecimalField(
    	verbose_name='Ціна',
    	max_digits=10,
    	decimal_places=4)
    quantity = models.PositiveIntegerField(
    	verbose_name='Кількість',
    	default=1)
    def get_cost(self):
    	return self.price * self.quantity
    def __unicode__(self):
		return u'%s' % (self.order)

shop/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Order


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, 
    	coerce=int, label="Кількість")
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

shop/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .models import Flower
from .models import Order, OrderItem
from .util import basket_list
from .util import flow_count_name
from .util import suma
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views.generic import UpdateView, CreateView, ListView, DeleteView
from django.forms import ModelForm
from django import forms
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from time import time
from .util import is_digit
from datetime import datetime
from .cart import Cart
from .forms import CartAddProductForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger







###########################################################################
def main_page(request):
  cart = Cart(request)
  flowers = Flower.objects.all()
  fl_count = flow_count_name(request)
  count = len(Cart(request))
  #pagination
  paginator = Paginator(flowers, 4)
  page = request.GET.get('page')
  try:
    flowers = paginator.page(page)
  except PageNotAnInteger:
    flowers = paginator.page(1)
  except EmptyPage:
    flowers= paginator.page(paginator.num_pages)
  return render(request, 'shop/main.html', {'flowers':flowers, 'count': count,
     'fl_count': fl_count, 'count': count, 'cart': cart})
  





def CartAdd(request, flower_id):
    cart = Cart(request)
    flower = get_object_or_404(Flower, id=flower_id)
    cart.add(flower=flower, quantity=1)
    return redirect('main')




def CartAdd_basket(request, flower_id):
    cart = Cart(request)
    flower = get_object_or_404(Flower, id=flower_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(flower=flower, quantity=cd['quantity'],
                                  update_quantity=cd['update'])
    return redirect('basket')





def CartRemove(request, flower_id):
    cart = Cart(request)
    flower = get_object_or_404(Flower, id=flower_id)
    cart.remove(flower)
    return redirect('basket')






def basket(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                                        initial={
                                            'quantity': item['quantity'],
                                            'update': True
                                        })
    return render(request, 'shop/basket.html', {'cart': cart})

#####################################################################
def about_me(request):
	return render(request, 'shop/about.html', {})


####################################################################
def contacts(request):
	return render(request, 'shop/contacts.html', {})





################################################################

#order_confirm


def OrderCreate(request):
    cart = Cart(request)
    if request.method == 'POST':
        errors = {}
        data = {}

        # validate user input
        name = request.POST.get('name', '').strip()
        if not name:
          errors['name'] = u"Ім'я є обов'язковим"
        else:
          data['name'] = name

        number = request.POST.get('number', '').strip()
        if not number:
          errors['number'] = u"Номер телефону є обов'язковим"
        else:
          data['number'] = number

        notes = request.POST.get('notes', '').strip()
        if notes:
          data['notes'] = notes
        
        total_cost = request.POST.get('total_cost', '').strip()
        data['total_cost'] = total_cost
        
        if not errors:
          order = Order(**data)
          order.save()
          for item in cart:
            OrderItem.objects.create(order=order, product=item['flower'],
                                         price=item['price'],
                                         quantity=item['quantity'])
          cart.clear()
          return HttpResponseRedirect( u'%s?status_message=Замовлення успішно збережено!' 
              % reverse('main'))
        else:
          return render(request, 'shop/ordering.html',
            {'errors': errors})

    return render(request, 'shop/ordering.html', {'cart': cart})


#####################################################################
def one_flower(request, pk):
  flower = Flower.objects.filter(pk=pk)
  fl_count = flow_count_name(request)
  count = len(basket_list(request))
  return render(request, 'shop/one_flower.html', {'flower':flower, 'count': count, 'fl_count': fl_count})









######################################################################
@login_required
def orders(request):
  orders = Order.objects.all()
  return render(request, 'shop/orders.html', {'orders': orders})




#########################################################################
#flower_add

def flower_add(request):
  # was form posted?
  if request.method == "POST":
    # was form add button clicked?
    if request.POST.get('add_button') is not None:
      # errors collection
      errors = {}
      # data for student object
      data = {}
      # validate user input
      title = request.POST.get('title', '').strip()
      if not title:
        errors['title'] = u"Ім'я є обов'язковим"
      else:
        data['title'] = title

      data['lat_title'] = time()
        
        
      price = request.POST.get('price', '').strip()
      if not price:
          errors['price'] = u"Ціна є обов'язковою"
      else:
          if is_digit(price) == 1:
            data['price'] = price
          else:
            errors['price'] = u"Введіть ціле число!"
      description = request.POST.get('description', '').strip()
      if not description:
        errors['description'] = u"Опис є обов'язковим"
      else:
        data['description'] = description  
      photo_main = request.FILES.get('photo_main')
      if not photo_main:
        errors['photo_main'] = u"Одне фото є обов'язковим"
      else:
        data['photo_main'] = photo_main 
      photo_big = request.FILES.get('photo_big')
      if photo_big:
        data['photo_big'] = photo_big 

           
      # save flovwer
      if not errors:
        flower = Flower(**data)
        flower.save()
        # redirect to students list
        return HttpResponseRedirect( u'%s?status_message=Квітку успішно додано!'  % reverse('main'))
      else:
        # render form with errors and previous user input
        return render(request, 'shop/flower_add.html',
        {'errors': errors})
    elif request.POST.get('cancel_button') is not None:
      # redirect to home page on cancel button
      return HttpResponseRedirect( u'%s?status_message=Додавання квітки скасовано!' % reverse('main'))
  else:
   # initial form render
   return render(request, 'shop/flower_add.html', {})




#####################################################################
#flower_edit


def flower_edit(request, pk):
    flower = Flower.objects.filter(pk=pk)

    
    if request.method == "POST":
        data = Flower.objects.get(pk=pk)
        if request.POST.get('add_button') is not None:
            
            errors = {}

            title = request.POST.get('title', '').strip()
            if not title:
                errors['title'] = u"Імʼя є обовʼязковим."
            else:
                data.title = title

            data.lat_title = time()

            price = request.POST.get('price', '').strip()
            if not price:
               errors['price'] = u"Ціна є обов'язковою"
            else:
               if is_digit(price) == 1:
                 data.price = price 
               else:
                 errors['price'] = u"Введіть ціле число!"

            description = request.POST.get('description', '').strip()
            if not description:
               errors['description'] = u"Опис є обов'язковим"
            else:
               data.description = description
            photo_main = request.FILES.get('photo_main')
            if not photo_main:
                errors['photo_main'] = u"Одне фото є обов'язковим"
            else:
                data.photo_main = photo_main 
            photo_big = request.FILES.get('photo_big')
            if photo_big:
               data.photo_big = photo_big 


            if errors:
                return render(request, 'shop/flower_edit.html', {'pk': pk, 'flower': data, 'errors': errors})
            else:
                data.save()
                return HttpResponseRedirect(u'%s?status_message=Редагування квітки  завершено' % reverse('main'))
        elif request.POST.get('cancel_button') is not None:

            return HttpResponseRedirect(u'%s?status_message=Редагування квітки скасовано!' % reverse('main'))
        
    else:
        return render(request,
                      'shop/flower_edit.html', {'pk': pk, 'flower': flower[0]})
                      
                      
                    






########################################

#flower delete

class FlowerDelete(DeleteView):
  model = Flower
  template_name = 'shop/flower_delete.html'
  def get_success_url(self):
    return u'%s?status_message=Квітку успішно видалено!' % reverse('main')
  def post(self, request, *args, **kwargs):
    if request.POST.get('no_delete_button'):
      return HttpResponseRedirect(u'%s?status_message=Видалення  квітки відмінено!'% reverse('main'))
    else:
      return super(FlowerDelete, self).post(request, *args, **kwargs)
  @method_decorator(login_required)
  def dispatch(self, *args, **kwargs):
        return super(FlowerDelete, self).dispatch(*args, **kwargs)




###############################################################################

def one_order(request, pk):
  order = Order.objects.get(pk=pk)
  products = OrderItem.objects.filter(order=order)

shop/templates/shop/about.html
{% extends 'shop/base.html' %}
{% load static from staticfiles %}



<title>{% block title %}Купівля насіння та саджанців квітів{% endblock title %}</title>


{% block content %}


 

{% endblock content %}


    




    

shop/templates/shop/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang='uk'>
  <head>
  	<meta charset='UTF-8'/>
    <title>Квітка</title>
  	<meta name='description'
      value='Про квіти' />
      <!-- Include Styles -->
      <link rel='stylesheet' href='https://cdn.jsdelivr.net/bootstrap/3.3.0/css/bootstrap.min.css'>
      <link rel="stylesheet" href='{% static 'css/my.css' %}'>
      {% block extra_css %}{% endblock extra_css %}
  </head>
  <body class="body">

<div id='registration'>
{% if user.is_authenticated %}
 {{ user.username }} |
   <a href='{% url 'users:auth_logout' %}'>Вийти</a>
{% else %}
   <a href='{% url 'users:auth_login' %}'>Ввійти</a>
{% endif %}
</div>

  	<!-- Logo -->
  	<div class="row">
    <div class='col-xs-12'>
      <h1 id='title'>{% block title %}{% endblock title %}</h1>



    </div>
    </div>

    <!-- Start SubHeader -->
    <div class='row' id='sub-header'>
      <div class='col-xs-12'>
       <ul class='nav nav-pills' role='tablist'>
        <li role='presentation' {% if request.path == '/' %}class="active"{% endif %}><a href='{% url 'main' %}'>Саджанці та насіння</a></li>
        <li role='presentation' {% if '/pro_mene' in request.path %}class="active"{% endif %}><a href='{% url 'about' %}'>Про мене</a></li>
        <li role='presentation' {% if '/kontakty' in request.path %}class="active"{% endif %}><a href='{% url 'contacts' %}'>Контакти</a></li>
        <li role='presentation' {% if '/koshyk' in request.path %}class="active"{% endif %}><a href='{% url 'basket' %}'>Кошик</a></li>
        {% if user.is_authenticated %}
        <li role='presentation' {% if '/samovlenya' in request.path %}class="active"{% endif %}><a href='{% url 'orders' %}'>готові замовлення</a></li>
        {% endif %}
       </ul>
      </div>
    </div>
    <!-- End SubHeader -->

     <div class="col-xs-12" id="content-column">
    
    {% block content %}{% endblock content %}

    

    <!-- Modal Boilerplate -->
   <div class="modal fade" id="myModal" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
     <div class="modal-dialog">
     <div class="modal-content">
     <div class="modal-header">
     <button type="button" class="close" data-dismiss="modal"
      aria-label="Close">
     <span aria-hidden="true">&times;</span></button>
     

     </div>
     <div class="modal-body"><!-- --></div>
     <div class="modal-footer"><!-- --></div>
     </div>
     </div>
   </div>

  </div>

  	<!-- Start Footer -->
    <div class="row">
      <footer>&copy; 2017 Oleh Smolynets</footer>
      </div>
        
<!-- End Footer -->
  	<!-- Javascripts Section -->
  	<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.js'></script>
    <script 
src="http://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.2.1/jquery.form.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"></script>
  	<script src='https://cdn.jsdelivr.net/bootstrap/3.3.0/js/bootstrap.min.js'></script>
    <script src="{% static "js/main.js" %}"></script>
  </body>
<html>

shop/templates/shop/basket.html
{% extends "shop/base.html" %}

{% block title %}
  
{% endblock %}

{% block content %}
{% if cart %}

<h2 id='basket_title'>В кошику</h2>

  <div class='row col-xs-8 col-xs-offset-2'>
 <table class="table">

  <thead>
   <tr>
    <th>Назва</th>
    <th>Кількість</th>
    <th>Ціна</th>
    <th>Повна ціна</th>
   </tr>
  </thead>

  <tbody>
  {% for item in cart %}
        {% with flower=item.flower %}
  <tr>
   <td>{{ flower.title }}</td>
   <td>
      <form action="{% url "CartAdd_basket" flower.id %}" method="post" class="add">
    {{ item.update_quantity_form.quantity }}
    {{ item.update_quantity_form.update }}
    {% csrf_token %}
    <input type="submit" value="Обновити">
</form>
   </td>
   <td>{{ item.price }} грн</td>
   <th>{{ item.total_price }}грн</th>
   <td>
   <a href="{% url "CartRemove" flower.id %}">Видалити
  </td>
   </tr>
  {% endwith %}
      {% endfor %}
      <td class="num">Загальна сума {{ cart.get_total_price }} грн.</td>
  </tbody>
 </table>
 </div>
 </div>


 
<div id='basket_button' class='row col-xs-8 col-xs-offset-2'>
 <a href='{% url 'main' %}' class="btn btn-primary">повернутись</a>
 <a href="{% url "OrderCreate" %}" class="btn btn-primary">замовити</a>
</div>


{% else %}
 <div class="alert alert-warning">
 Ви не вибрали жодного товару
 </div>

 {% endif %}
{% endblock content %}

shop/templates/shop/contacts.html
{% extends 'shop/base.html' %}
{% load static from staticfiles %}



<title>{% block title %}Купівля насіння та саджанців квітів{% endblock title %}</title>


{% block content %}


 

{% endblock content %}


    




    

shop/templates/shop/flower_add.html
{% extends 'shop/base.html' %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}
{% block meta_title %}{% endblock meta_title %}
{% block title %}Додавання квітки{% endblock title %}
{% block status_message %}
{% if errors %}
<div class="alert alert-warning" role="alert">
Будь-ласка, виправте наступні помилки
</div>
{% endif %}
{% endblock status_message %}
{% block content %}
<div class="add_form">





<form action="{% url "flower_add" %}" method="post"
enctype="multipart/form-data" role="form" class="form-horizontal form-add_edit">
{% csrf_token %}

<div class="form-group {% if errors.title %}has-error{% endif%}">
  <label for="title" class="col-sm-2 control-label">Назва*</label>
  <div class="col-sm-10">
    <input type="text" value="{{ request.POST.title }}"
    name="title" id="title" class="form-control" />
     <span class="help-block">{{ errors.title }}</span>
  </div>
</div>

<div class="form-group {% if errors.price %}has-error{% endif%}">
  <label for="price" class="col-sm-2 control-label">Ціна*(тільки цифри!)</label>
  <div class="col-sm-10">
   <input type="text" value="{{ request.POST.price }}"
    name="price" id="price" class="form-control" />
  <span class="help-block">{{ errors.price }}</span>
  </div>
</div>

<div class="form-group {% if errors.description %}has-error{% endif %}">
    <label for="description" class="col-sm-2 control-label">Опис*</label>
    <div class="col-sm-10">
      <textarea name="description" id="description" class="form-control">{{ request.POST.description }}</textarea>
      <span class="help-block">{{ errors.description }}</span>
    </div>
  </div>

<div class="form-group {% if errors.photo_main %}has-error{% endif %}">
    <label for="photo"class="col-sm-2 control-label">Фото головне*</label>
    <div class="col-sm-10">
      <input type="file" value="" name="photo_main" id="photo_main"
             class="form-control" />
      <span class="help-block">{{ errors.photo_main }}</span>
    </div>
  </div>


<div class="form-group {% if errors.photo_big %}has-error{% endif %}">
    <label for="photo_big"class="col-sm-2 control-label">Фото 2</label>
    <div class="col-sm-10">
      <input type="file" value="" name="photo_big" id="photo_big"
             class="form-control" />
      <span class="help-block">{{ errors.photo_big }}</span>
    </div>
  </div>

<div class="form-group">
  <label class="col-sm-2 control-label"></label>
  <div class="col-sm-10">
  <input type="submit" value="Додати" name="add_button"
    class="btn btn-primary" />
  <button type="submit" name="cancel_button"
    class="btn btn-link">Скасувати</button>
  </div>
  </div>
</form>





<p>Поля, позначені  зірочкою,  обовязкові  для  заповнення!</p>
</div>
{% endblock content %}

shop/templates/shop/flower_delete.html
{% extends "shop/base.html" %}
{% load static from staticfiles %}
{% block meta_title %}Видалення квітки{% endblock meta_title %}
{% block title %}Видалити квітку{% endblock title %}
{% block content %}
<div id='del_confirm'>
<form action="" method="post">
{% csrf_token %}
<p>Ви дійсно хочете видалити квітку "{{ object }}"?</p>
<input type="submit" value="Так" name="delete_button"
class="btn btn-danger" />
<input type="submit" value="Ні" name="no_delete_button"
class="btn btn-danger" /><br /><br />
</form>
</div>
{% endblock content %}

shop/templates/shop/flower_edit.html
{% extends 'shop/base.html' %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}
{% block meta_title %}{% endblock meta_title %}
{% block title %}Редагування квітки{% endblock title %}
{% block status_message %}
{% if errors %}
<div class="alert alert-warning" role="alert">
Будь-ласка, виправте наступні помилки
</div>
{% endif %}
{% endblock status_message %}
{% block content %}
<div class="add_form">





<form action="{% url "flower_edit" pk %}" method="post"
enctype="multipart/form-data" role="form" class="form-horizontal form-add_edit">
{% csrf_token %}

<div class="form-group {% if errors.title %}has-error{% endif%}">
  <label for="title" class="col-sm-2 control-label">Назва*</label>
  <div class="col-sm-10">
    <input type="text" value="{{ flower.title }}"
    name="title" id="title" class="form-control" />
     <span class="help-block">{{ errors.title }}</span>
  </div>
</div>

<div class="form-group {% if errors.price %}has-error{% endif%}">
  <label for="price" class="col-sm-2 control-label">Ціна*(тільки цифри!)</label>
  <div class="col-sm-10">
   <input type="text" value="{{ flower.price }}"
    name="price" id="price" class="form-control" />
  <span class="help-block">{{ errors.price }}</span>
  </div>
</div>

<div class="form-group {% if errors.description %}has-error{% endif %}">
    <label for="description" class="col-sm-2 control-label">Опис</label>
    <div class="col-sm-10">
      <textarea name="description" id="description" class="form-control">{{ flower.description }}</textarea>
      <span class="help-block">{{ errors.description }}</span>
    </div>
  </div>

<div class="form-group {% if errors.photo_main %}has-error{% endif %}">
    <label for="photo"class="col-sm-2 control-label">Фото головне</label>
    <div class="col-sm-10">
      <input type="file" value="" name="photo_main" id="photo_main"
             class="form-control" />
      <span class="help-block">{{ errors.photo_main }}</span>
    </div>
  </div>


<div class="form-group {% if errors.photo_big %}has-error{% endif %}">
    <label for="photo_big"class="col-sm-2 control-label">Фото 2</label>
    <div class="col-sm-10">
      <input type="file" value="" name="photo_big" id="photo_big"
             class="form-control" />
      <span class="help-block">{{ errors.photo_big }}</span>
    </div>
  </div>

<div class="form-group">
  <label class="col-sm-2 control-label"></label>
  <div class="col-sm-10">
  <input type="submit" value="Зберегти" name="add_button"
    class="btn btn-primary" />
  <button type="submit" name="cancel_button"
    class="btn btn-link">Скасувати</button>
  </div>
  </div>
</form>





<p>Поля, позначені  зірочкою,  обовязкові  для  заповнення!</p>
</div>
{% endblock content %}

shop/templates/shop/main.html
{% extends 'shop/base.html' %}
{% load static from staticfiles %}



<title>{% block title %}Купівля насіння та саджанців квітів{% endblock title %}</title>

    {% block content %}
    {% if request.GET.status_message %}
          <div class="alert alert-warning" role="alert">{{ request.GET.status_message }}</div>
    {% else %}
    <div class="alert alert-warning">
       {% with total_items=cart|length %}
        {% if cart|length > 0 %}
            В вашому кошику 
            <a href="{% url "basket" %}">
                {{ total_items }} од.
            </a>
         {% else %}
              Кошик пустий
        {% endif %}
    {% endwith %}
    {% endif %}
</div>

{% if user.is_authenticated %}
<a class='btn btn-primary btn1' href='{% url "flower_add" %}'>додати квітку</a>
{% endif %}
    <!-- Start Listing -->
   <!-- <div class='row main_list'>-->
   <div class='row col-xs-10 col-xs-offset-1'>

      {% for fl in flowers %}
             <div class="col-xs-3 lot">
                <div class="thumbnail">
                    <img src="{{ fl.photo_main.url }}" alt="">
                    <div class="title_lot"><h4>{{ fl.title }}</h4></div>
                    <div class="caption">
                        <div id='price_buy'>ціна {{ fl.price }} грн</div>
            <div>
      <a href='{% url 'CartAdd' fl.id %}' class="btn btn-primary to_basket">в кошик</a>
            </div>
            <div id='reade_more'><a href="{% url "one_flower" fl.id %}">Читати 
більше...</a></div>
                    </div>
                </div>
            </div>

      {% endfor %}

    </div>



<div class='row col-xs-10 col-xs-offset-1'>
<nav>
<ul class="pagination">
<li><a href="#">&laquo;</a></li>

{% for p in flowers.paginator.page_range %}
<li {% if flowers.number == p %}class="active"{% endif %}>
<a href="{% url "main" %}?page={{ p }}&amp;order_by={{ order_by }}&amp;reverse={{ reverse }}">{{ p }}</a>
</li>
{% endfor %}

<li><a href="#">&raquo;</a></li>
</ul>
</nav>
</div>
    {% endblock content %}

shop/templates/shop/one_order.html
{% extends 'shop/base.html' %}
{% load static from staticfiles %}

<title>{% block title %}Купівля насіння та саджанців квітів{% endblock title %}</title>


{% block content %}
    

 <div id='one_order'>
  <table class="table">
  <tbody>
  <tr>
  <td>імя</td>
  <td>{{ order.name }}</td>
  </tr>
  <tr>
  <td>телефон</td>
  <td>{{ order.number }}</td>
  </tr>
  <tr>
  <td>Додаткові нотатки</td>
  <td>{{ order.note }}</td>
  </tr>
  </tbody>
  </table>
<table>
<tbody>
  {% for item in products %}
  <tr>
  <td>
    {{item.product}}
  </td>
  <td>
    {{item.quantity}}
  </td>
  </tr>
  {% endfor %}
  </tbody>
  </table>
  </div>
 </div>




{% endblock content %}
    




  	
  	

shop/templates/shop/orders.html
{% extends 'shop/base.html' %}
{% load static from staticfiles %}



<title>{% block title %}Купівля насіння та саджанців квітів{% endblock title %}</title>

    {% block content %}
    

      
<table class="table">

 <tr>
 <th>
  #
 </th>
 <th>
  імя
 </th>
 <th>
  телефон
 </th>
 <th>
  сума
 </th>
 </tr>
 </thead>

<tbody>

{% for order in orders %}
 <tr>

  <td><a href='{% url 'one_order' order.id %}'>{{ forloop.counter }}</td>
  <td><a href='{% url 'one_order' order.id %}'>{{ order.name }}</td>
  <td><a href='{% url 'one_order' order.id %}'>{{ order.number }}</td>
  <td><a href='{% url 'one_order' order.id %}'>{{ order.total_cost }}</td>

 </tr>
{% endfor %}

</tbody>
</table>



    {% endblock content %}


    




    